import * as LucideIcons from 'lucide-react'

export type IconName = keyof typeof iconMap

// Popular icons that can be selected in the admin
export const iconMap = {
  Sparkles: LucideIcons.Sparkles,
  Star: LucideIcons.Star,
  Trophy: LucideIcons.Trophy,
  Award: LucideIcons.Award,
  Heart: LucideIcons.Heart,
  Zap: LucideIcons.Zap,
  Flame: LucideIcons.Flame,
  Sun: LucideIcons.Sun,
  Moon: LucideIcons.Moon,
  Cloud: LucideIcons.Cloud,
  Rocket: LucideIcons.Rocket,
  Target: LucideIcons.Target,
  TrendingUp: LucideIcons.TrendingUp,
  Activity: LucideIcons.Activity,
  BarChart: LucideIcons.BarChart,
  PieChart: LucideIcons.PieChart,
  Users: LucideIcons.Users,
  User: LucideIcons.User,
  UserPlus: LucideIcons.UserPlus,
  Building: LucideIcons.Building,
  Building2: LucideIcons.Building2,
  Home: LucideIcons.Home,
  Briefcase: LucideIcons.Briefcase,
  ShoppingBag: LucideIcons.ShoppingBag,
  ShoppingCart: LucideIcons.ShoppingCart,
  CreditCard: LucideIcons.CreditCard,
  DollarSign: LucideIcons.DollarSign,
  Globe: LucideIcons.Globe,
  MapPin: LucideIcons.MapPin,
  Navigation: LucideIcons.Navigation,
  Compass: LucideIcons.Compass,
  Send: LucideIcons.Send,
  Mail: LucideIcons.Mail,
  Phone: LucideIcons.Phone,
  MessageCircle: LucideIcons.MessageCircle,
  Bell: LucideIcons.Bell,
  Calendar: LucideIcons.Calendar,
  Clock: LucideIcons.Clock,
  BookOpen: LucideIcons.BookOpen,
  Book: LucideIcons.Book,
  FileText: LucideIcons.FileText,
  File: LucideIcons.File,
  Folder: LucideIcons.Folder,
  Code: LucideIcons.Code,
  Cpu: LucideIcons.Cpu,
  Database: LucideIcons.Database,
  Server: LucideIcons.Server,
  Wifi: LucideIcons.Wifi,
  Monitor: LucideIcons.Monitor,
  Smartphone: LucideIcons.Smartphone,
  Tablet: LucideIcons.Tablet,
  Camera: LucideIcons.Camera,
  Image: LucideIcons.Image,
  Video: LucideIcons.Video,
  Music: LucideIcons.Music,
  Headphones: LucideIcons.Headphones,
  Play: LucideIcons.Play,
  Pause: LucideIcons.Pause,
  Settings: LucideIcons.Settings,
  Wrench: LucideIcons.Wrench,
  Package: LucideIcons.Package,
  Box: LucideIcons.Box,
  Gift: LucideIcons.Gift,
  Tag: LucideIcons.Tag,
  Bookmark: LucideIcons.Bookmark,
  Flag: LucideIcons.Flag,
  CheckCircle: LucideIcons.CheckCircle,
  XCircle: LucideIcons.XCircle,
  AlertCircle: LucideIcons.AlertCircle,
  Info: LucideIcons.Info,
  HelpCircle: LucideIcons.HelpCircle,
  Lightbulb: LucideIcons.Lightbulb,
  Key: LucideIcons.Key,
  Lock: LucideIcons.Lock,
  Unlock: LucideIcons.Unlock,
  Shield: LucideIcons.Shield,
  Eye: LucideIcons.Eye,
  EyeOff: LucideIcons.EyeOff,
  Search: LucideIcons.Search,
  Filter: LucideIcons.Filter,
  Download: LucideIcons.Download,
  Upload: LucideIcons.Upload,
  Share: LucideIcons.Share,
  Link: LucideIcons.Link,
  ExternalLink: LucideIcons.ExternalLink,
  Maximize: LucideIcons.Maximize,
  Minimize: LucideIcons.Minimize,
  Plus: LucideIcons.Plus,
  Minus: LucideIcons.Minus,
  X: LucideIcons.X,
  Check: LucideIcons.Check,
  ChevronRight: LucideIcons.ChevronRight,
  ChevronLeft: LucideIcons.ChevronLeft,
  ChevronUp: LucideIcons.ChevronUp,
  ChevronDown: LucideIcons.ChevronDown,
  ArrowRight: LucideIcons.ArrowRight,
  ArrowLeft: LucideIcons.ArrowLeft,
  ArrowUp: LucideIcons.ArrowUp,
  ArrowDown: LucideIcons.ArrowDown,
} as const

// Get icon options for select field
export const iconOptions = Object.keys(iconMap).map((iconName) => ({
  label: iconName,
  value: iconName,
}))

// Get icon component by name
export const getIcon = (iconName: IconName | string) => {
  return iconMap[iconName as IconName] || LucideIcons.Sparkles
}
