/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
collections: {
  users: User
  media: Media
  'media-folders': MediaFolder
  navigation: Navigation
  pages: Page
  'contact-submissions': ContactSubmission
}
globals: {
  'site-settings': SiteSettings
  footer: Footer
}
}

/**
 * User
 */
export interface User {
id: string
name: string
email: string
role: 'admin' | 'user'
avatar?: string | Media | null
createdAt: string
updatedAt: string
}

/**
 * Media
 */
export interface Media {
id: string
folder?: string | MediaFolder | null
alt: string
caption?: string | null
uploadedBy?: string | User | null
url?: string | null
filename?: string | null
mimeType?: string | null
filesize?: number | null
width?: number | null
height?: number | null
focalX?: number | null
focalY?: number | null
sizes?: {
  thumbnail?: {
    url?: string | null
    width?: number | null
    height?: number | null
  }
  card?: {
    url?: string | null
    width?: number | null
    height?: number | null
  }
  tablet?: {
    url?: string | null
    width?: number | null
    height?: number | null
  }
}
createdAt: string
updatedAt: string
}

/**
 * MediaFolder
 */
export interface MediaFolder {
id: string
name: string
slug: string
parent?: string | MediaFolder | null
createdAt: string
updatedAt: string
}

/**
 * Navigation
 */
export interface Navigation {
id: string
label: string
linkType?: 'none' | 'page' | 'custom' | null
page?: string | Page | null
href?: string | null
order: number
openInNewTab?: boolean | null
children?: NavigationChild[] | null
createdAt: string
updatedAt: string
}

export interface NavigationChild {
label: string
items?: NavigationChildItem[] | null
}

export interface NavigationChildItem {
label: string
linkType: 'page' | 'custom'
page?: string | Page | null
href?: string | null
openInNewTab?: boolean | null
}

/**
 * Page
 */
export interface Page {
id: string
title: string
pageType: 'home' | 'news' | 'leadership' | 'departments' | 'documents' | 'text'
status: 'draft' | 'published' | 'archived'
slug?: string | null
content?: Record<string, unknown> | null
blocks?: PageBlock[] | null
seo?: SEOFields | null
publishedDate?: string | null
author?: string | User | null
createdAt: string
updatedAt: string
}

export type PageBlock = HeroBlock | FAQBlock | SectionHeaderBlock | RichTextBlock | ServiceCardsBlock | AboutBlock | ValueCardsBlock | CaseCardsBlock

export interface HeroBlock {
id?: string | null
blockType: 'heroBlock'
anchorId?: string | null
layout: 'centered' | 'split-left' | 'split-right'
background?: {
  type?: 'color' | 'gradient' | 'image' | null
  color?: string | null
  gradient?: string | null
  image?: string | Media | null
  overlay?: boolean | null
  overlayOpacity?: number | null
} | null
badge?: {
  text?: string | null
  icon?: string | null
  gradient?: string | null
} | null
headline: string
subheadline?: string | null
bulletPoints?: {
  id?: string | null
  icon?: string | null
  text: string
}[] | null
primaryCTA?: {
  label?: string | null
  linkType?: ('page' | 'external' | 'anchor') | null
  page?: (string | null) | Page
  url?: string | null
  anchor?: string | null
  style?: 'solid' | 'outline' | null
  openInNewTab?: boolean | null
} | null
secondaryCTA?: {
  label?: string | null
  linkType?: ('page' | 'external' | 'anchor') | null
  page?: (string | null) | Page
  url?: string | null
  anchor?: string | null
  style?: 'solid' | 'outline' | null
  openInNewTab?: boolean | null
} | null
trustBadges?: {
  id?: string | null
  image: string | Media
  alt?: string | null
}[] | null
heroImage?: string | Media | null
enableAnimation?: boolean | null
}

export interface FAQBlock {
id?: string | null
blockType: 'faqBlock'
anchorId?: string | null
title?: string | null
questions: {
  id?: string | null
  question: string
  answer: string
}[]
allowMultiple?: boolean | null
enableAnimation?: boolean | null
}

export interface SectionHeaderBlock {
id?: string | null
blockType: 'sectionHeader'
anchorId?: string | null
type: 'small' | 'big'
layout?: 'centered' | 'left' | 'right' | null
title: string
subtitle?: string | null
description?: string | null
headingLevel?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | null
badge?: {
  text?: string | null
  icon?: string | null
  gradient?: string | null
} | null
background?: {
  type?: 'none' | 'color' | 'gradient' | 'image' | null
  color?: string | null
  gradient?: string | null
  image?: string | Media | null
  overlay?: boolean | null
  overlayOpacity?: number | null
} | null
bulletPoints?: {
  id?: string | null
  icon?: string | null
  text: string
}[] | null
primaryCTA?: {
  label?: string | null
  linkType?: ('page' | 'external' | 'anchor') | null
  page?: (string | null) | Page
  url?: string | null
  anchor?: string | null
  style?: 'solid' | 'outline' | null
  openInNewTab?: boolean | null
} | null
secondaryCTA?: {
  label?: string | null
  linkType?: ('page' | 'external' | 'anchor') | null
  page?: (string | null) | Page
  url?: string | null
  anchor?: string | null
  style?: 'solid' | 'outline' | null
  openInNewTab?: boolean | null
} | null
enableAnimation?: boolean | null
}

export interface RichTextBlock {
id?: string | null
blockType: 'richText'
content: Record<string, unknown> | null
}

export interface ServiceCardsBlock {
id?: string | null
blockType: 'serviceCardsBlock'
anchorId?: string | null
title?: string | null
cards: {
  id?: string | null
  title: string
  bulletPoints?: {
    id?: string | null
    text: string
  }[] | null
  ctaLabel?: string | null
  ctaLinkType?: ('page' | 'external' | 'anchor') | null
  ctaPage?: (string | Page) | null
  ctaUrl?: string | null
  ctaAnchor?: string | null
  ctaOpenInNewTab?: boolean | null
}[]
tags?: {
  id?: string | null
  text: string
}[] | null
enableAnimation?: boolean | null
}

export interface AboutBlock {
id?: string | null
blockType: 'aboutBlock'
anchorId?: string | null
title?: string | null
image?: string | Media | null
badges?: {
  id?: string | null
  emoji?: string | null
  text: string
}[] | null
description?: string | null
ctaLabel?: string | null
ctaLinkType?: ('page' | 'external' | 'anchor') | null
ctaPage?: (string | null) | Page
ctaUrl?: string | null
ctaAnchor?: string | null
ctaOpenInNewTab?: boolean | null
enableAnimation?: boolean | null
}

export interface ValueCardsBlock {
id?: string | null
blockType: 'valueCardsBlock'
anchorId?: string | null
title?: string | null
description?: string | null
tags?:
  | {
      id?: string | null
      text: string
    }[]
  | null
cards?:
  | {
      id?: string | null
      text: string
    }[]
  | null
enableAnimation?: boolean | null
}

export interface CaseCardsBlock {
id?: string | null
blockType: 'caseCardsBlock'
anchorId?: string | null
title?: string | null
displayMode?: ('cases' | 'reviews') | null
cases: {
  id?: string | null
  title: string
  sections: {
    id?: string | null
    emoji?: string | null
    label: string
    content: string
  }[]
}[]
reviews?:
  | {
      id?: string | null
      quote: string
      authorName: string
      authorSubtitle?: string | null
    }[]
  | null
enableAnimation?: boolean | null
}

/**
 * SEO Fields
 */
export interface SEOFields {
metaTitle?: string | null
focusKeyword?: string | null
metaDescription?: string | null
keywords?: string | null
canonicalUrl?: string | null
noIndex?: boolean | null
noFollow?: boolean | null
ogTitle?: string | null
ogDescription?: string | null
ogImage?: string | Media | null
ogType?: 'website' | 'article' | 'blog' | null
twitterCard?: 'summary_large_image' | 'summary' | null
twitterTitle?: string | null
twitterDescription?: string | null
twitterImage?: string | Media | null
metaImage?: string | Media | null
// Allow additional fields for compatibility
[key: string]: unknown
}

/**

/**
 */
/**
 * SiteSettings Global
 */
export interface SiteSettings {
id: string
siteTitle: string
siteLogo?: string | Media | null
logoAltText?: string | null
tagline?: string | null
socialLinks?: SocialLink[] | null
createdAt: string
updatedAt: string
}

export interface SocialLink {
platform:
  | 'facebook'
  | 'twitter'
  | 'instagram'
  | 'linkedin'
  | 'youtube'
  | 'tiktok'
  | 'github'
  | 'discord'
url: string
openInNewTab?: boolean | null
}

/**
 * Footer Global
 */
export interface Footer {
id: string
title?: string | null
// Contact Info tab
sectionTitle?: string | null
sectionSubtitle?: string | null
messengerLinks?: FooterMessengerLink[] | null
phoneLabel?: string | null
phoneNumber?: string | null
phoneHref?: string | null
emailLabel?: string | null
emailAddress?: string | null
emailHref?: string | null
disclaimer?: string | null
// Contact Form tab
formHeading?: string | null
formNamePlaceholder?: string | null
formPhonePlaceholder?: string | null
formEmailPlaceholder?: string | null
formOrganizationPlaceholder?: string | null
formMessagePlaceholder?: string | null
consentText?: string | null
submitButtonText?: string | null
successMessage?: string | null
errorMessage?: string | null
sendAnotherButtonText?: string | null
loadingText?: string | null
nameRequiredError?: string | null
emailRequiredError?: string | null
consentRequiredError?: string | null
// Bottom Bar tab
copyrightText?: string | null
createdAt: string
updatedAt: string
}

export interface FooterMessengerLink {
id?: string | null
platform: 'telegram' | 'viber' | 'whatsapp' | 'signal'
label: string
url: string
}

/**
 * ContactSubmission
 */
export interface ContactSubmission {
id: string
name: string
phone?: string | null
email: string
organization?: string | null
message?: string | null
consentGiven: boolean
locale?: string | null
status?: 'new' | 'in-progress' | 'resolved' | null
createdAt: string
updatedAt: string
}
