import type { CollectionConfig } from 'payload'
import { generateSlug } from '@/lib/transliterate'

/**
 * News Collection
 * News articles and updates that appear in carousels and news listings
 */
export const News: CollectionConfig = {
  slug: 'news',
  admin: {
    group: 'Content',
    defaultColumns: ['title', 'publishedDate', 'status', 'updatedAt'],
    useAsTitle: 'title',
    livePreview: {
      url: ({ data, locale }) => {
        const baseURL = process.env.NEXT_PUBLIC_SERVER_URL || 'http://localhost:3000'

        // Ensure locale is a string
        let docLocale: string
        if (typeof locale === 'string') {
          docLocale = locale
        } else if (locale && typeof locale === 'object') {
          docLocale = (locale as any).code || (locale as any).locale || 'uk'
        } else {
          docLocale = 'uk'
        }

        return `${baseURL}/${docLocale}/news/${data.slug}?preview=true`
      },
    },
    preview: (doc, { locale }) => {
      const baseURL = process.env.NEXT_PUBLIC_SERVER_URL || 'http://localhost:3000'

      // Ensure locale is a string
      let docLocale: string
      if (typeof locale === 'string') {
        docLocale = locale
      } else if (locale && typeof locale === 'object') {
        docLocale = (locale as any).code || (locale as any).locale || 'uk'
      } else {
        docLocale = 'uk'
      }

      return `${baseURL}/${docLocale}/news/${doc.slug}`
    },
  },
  versions: {
    drafts: {
      autosave: {
        interval: 375,
      },
    },
    maxPerDoc: 50,
  },
  access: {
    // Public read access for published items
    read: ({ req: { user } }) => {
      if (user) return true
      return {
        status: {
          equals: 'published',
        },
      }
    },
    // Authenticated users can create
    create: ({ req: { user } }) => !!user,
    // Authors can update their own, admins can update all
    update: ({ req: { user } }) => {
      if (!user) return false
      if (user.role === 'admin') return true
      return {
        author: {
          equals: user.id,
        },
      }
    },
    // Only admins can delete
    delete: ({ req: { user } }) => user?.role === 'admin',
  },
  fields: [
    // Basic Information
    {
      name: 'title',
      type: 'text',
      required: true,
      localized: true,
      admin: {
        description: 'Main headline for the news article',
      },
    },
    {
      name: 'slug',
      type: 'text',
      required: true,
      unique: true,
      admin: {
        description: 'URL-friendly identifier (auto-generated from title with Cyrillic transliteration)',
        position: 'sidebar',
      },
      hooks: {
        beforeValidate: [
          ({ data, operation, value, originalDoc }) => {
            // Auto-generate slug from title if:
            // 1. Creating a new document, OR
            // 2. Slug is empty, OR
            // 3. Slug matches what would be generated from title (auto-sync mode)
            const currentTitle = data?.title || ''
            const currentSlug = value || ''
            const autoGeneratedSlug = generateSlug(currentTitle)

            // On create, always auto-generate
            if (operation === 'create') {
              return autoGeneratedSlug
            }

            // On update, regenerate if slug is empty or matches auto-generated pattern
            if (operation === 'update') {
              // If slug is empty, generate from title
              if (!currentSlug) {
                return autoGeneratedSlug
              }

              // If slug matches what would be generated from current title, keep it in sync
              // This means user hasn't manually customized the slug
              if (currentSlug === autoGeneratedSlug) {
                return autoGeneratedSlug
              }

              // If slug was previously auto-generated from old title, update to new title
              if (originalDoc?.title) {
                const oldAutoSlug = generateSlug(originalDoc.title)
                if (currentSlug === oldAutoSlug) {
                  return autoGeneratedSlug
                }
              }

              // Otherwise, user has manually edited slug, keep it
              return currentSlug
            }

            return value
          },
        ],
      },
    },
    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'draft',
      admin: {
        position: 'sidebar',
      },
      options: [
        { label: 'Draft', value: 'draft' },
        { label: 'Published', value: 'published' },
      ],
    },

    // Dates
    {
      name: 'publishedDate',
      type: 'date',
      required: true,
      defaultValue: () => new Date().toISOString(),
      admin: {
        description: 'Date this news item was or will be published',
        position: 'sidebar',
        date: {
          displayFormat: 'MMMM d, yyyy',
          pickerAppearance: 'dayAndTime',
        },
      },
    },

    // Featured Image
    {
      name: 'featuredImage',
      type: 'upload',
      relationTo: 'media',
      required: false,
      admin: {
        description: 'Main image for carousel and listing (recommended: 1200x800px)',
      },
    },

    // Category/Tags
    {
      name: 'tags',
      type: 'relationship',
      relationTo: 'news-tags',
      hasMany: true,
      admin: {
        description: 'Categories for this news item (Innovation, Business, etc.)',
        position: 'sidebar',
      },
    },

    // Content
    {
      type: 'tabs',
      tabs: [
        {
          label: 'Content',
          description: 'Article content and layout blocks',
          fields: [
            {
              name: 'excerpt',
              type: 'textarea',
              required: true,
              localized: true,
              maxLength: 300,
              admin: {
                description: 'Brief summary (shown in cards and previews)',
                placeholder: 'Write a compelling summary in 1-2 sentences...',
              },
            },
            {
              name: 'blocks',
              type: 'blocks',
              localized: true,
              admin: {
                description: 'Flexible content blocks for article layout',
              },
              blocks: [
                {
                  slug: 'sectionHeader',
                  labels: {
                    singular: 'Section Header',
                    plural: 'Section Headers',
                  },
                  fields: [
                    {
                      name: 'type',
                      type: 'select',
                      required: true,
                      defaultValue: 'small',
                      admin: {
                        description: 'Header style: Small (section headers) or Big (hero-style headers)',
                      },
                      options: [
                        {
                          label: 'Small - Section Header',
                          value: 'small',
                        },
                        {
                          label: 'Big - Hero Header',
                          value: 'big',
                        },
                      ],
                    },
                    {
                      name: 'title',
                      type: 'text',
                      required: true,
                      admin: {
                        description: 'Main heading text (required)',
                      },
                    },
                    {
                      name: 'subtitle',
                      type: 'text',
                      admin: {
                        description: 'Secondary text below the title (optional)',
                      },
                    },
                    {
                      name: 'description',
                      type: 'textarea',
                      admin: {
                        description: 'Additional description text (optional)',
                      },
                    },
                    {
                      name: 'headingLevel',
                      type: 'select',
                      defaultValue: 'h2',
                      admin: {
                        description: 'HTML heading level for SEO',
                      },
                      options: [
                        { label: 'H1', value: 'h1' },
                        { label: 'H2', value: 'h2' },
                        { label: 'H3', value: 'h3' },
                        { label: 'H4', value: 'h4' },
                        { label: 'H5', value: 'h5' },
                        { label: 'H6', value: 'h6' },
                      ],
                    },
                    {
                      name: 'badge',
                      type: 'group',
                      admin: {
                        description: 'Optional badge displayed above the title',
                      },
                      fields: [
                        {
                          name: 'text',
                          type: 'text',
                          admin: {
                            description: 'Badge text (e.g., "Featured Content")',
                          },
                        },
                        {
                          name: 'icon',
                          type: 'text',
                          admin: {
                            description: 'Icon displayed in the badge',
                            components: {
                              Field: '@/fields/IconSelectField#IconSelectField',
                            },
                          },
                        },
                        {
                          name: 'gradient',
                          type: 'text',
                          admin: {
                            description: 'Gradient color scheme for the badge',
                            components: {
                              Field: '@/fields/GradientSelectField#GradientSelectField',
                            },
                          },
                        },
                      ],
                    },
                    {
                      name: 'enableAnimation',
                      type: 'checkbox',
                      defaultValue: true,
                      admin: {
                        description: 'Enable fade-in animation on page load',
                      },
                    },
                  ],
                },
                {
                  slug: 'richText',
                  labels: {
                    singular: 'Rich Text Block',
                    plural: 'Rich Text Blocks',
                  },
                  fields: [
                    {
                      name: 'content',
                      type: 'richText',
                      required: true,
                    },
                  ],
                },
                {
                  slug: 'markdownText',
                  labels: {
                    singular: 'Markdown Rich Text Block',
                    plural: 'Markdown Rich Text Blocks',
                  },
                  fields: [
                    {
                      name: 'markdown',
                      type: 'textarea',
                      required: true,
                      admin: {
                        description: 'Use the visual markdown editor below. Live preview is shown on the right side.',
                        components: {
                          Field: '@/fields/MarkdownEditorField#MarkdownEditorField',
                        },
                      },
                    },
                    {
                      name: 'accentColor',
                      type: 'select',
                      defaultValue: 'amber',
                      admin: {
                        description: 'Color scheme for blockquotes and accents',
                      },
                      options: [
                        { label: 'Amber', value: 'amber' },
                        { label: 'Indigo', value: 'indigo' },
                        { label: 'Purple', value: 'purple' },
                        { label: 'Green', value: 'green' },
                        { label: 'Blue', value: 'blue' },
                      ],
                    },
                  ],
                },
                {
                  slug: 'imageBlock',
                  labels: {
                    singular: 'Image Block',
                    plural: 'Image Blocks',
                  },
                  fields: [
                    {
                      name: 'image',
                      type: 'upload',
                      relationTo: 'media',
                      required: true,
                    },
                    {
                      name: 'caption',
                      type: 'text',
                    },
                  ],
                },
                {
                  slug: 'callToAction',
                  labels: {
                    singular: 'Call to Action',
                    plural: 'Call to Actions',
                  },
                  fields: [
                    {
                      name: 'heading',
                      type: 'text',
                      required: true,
                    },
                    {
                      name: 'description',
                      type: 'textarea',
                    },
                    {
                      name: 'link',
                      type: 'group',
                      fields: [
                        {
                          name: 'label',
                          type: 'text',
                          required: true,
                        },
                        {
                          name: 'url',
                          type: 'text',
                          required: true,
                        },
                        {
                          name: 'openInNewTab',
                          type: 'checkbox',
                          defaultValue: false,
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          label: 'SEO',
          description: 'Search engine optimization and social media settings',
          fields: [
            {
              name: 'seo',
              type: 'group',
              label: false,
              fields: [
                // SEO Validation Score
                {
                  name: 'seoValidation',
                  type: 'ui',
                  admin: {
                    components: {
                      Field: '@/fields/SEOValidationField#SEOValidationField',
                    },
                  },
                },

                // Basic SEO
                {
                  type: 'row',
                  fields: [
                    {
                      name: 'metaTitle',
                      type: 'text',
                      localized: true,
                      admin: {
                        placeholder: 'Override title for search engines',
                        description: 'Optimal length: 50-60 characters. Leave empty to use article title.',
                      },
                      maxLength: 70,
                    },
                    {
                      name: 'focusKeyword',
                      type: 'text',
                      localized: true,
                      admin: {
                        placeholder: 'e.g., "business innovation"',
                        description: 'Main keyword this article should rank for',
                      },
                    },
                  ],
                },
                {
                  name: 'metaDescription',
                  type: 'textarea',
                  localized: true,
                  admin: {
                    placeholder: 'Brief description for search results...',
                    description: 'Optimal length: 150-160 characters. Falls back to excerpt if empty.',
                  },
                  maxLength: 200,
                },
                {
                  name: 'keywords',
                  type: 'text',
                  localized: true,
                  admin: {
                    placeholder: 'keyword1, keyword2, keyword3',
                    description: 'Comma-separated keywords related to this article',
                  },
                },

                // Advanced SEO Settings
                {
                  type: 'collapsible',
                  label: 'Advanced SEO Settings',
                  admin: {
                    initCollapsed: true,
                  },
                  fields: [
                    {
                      name: 'canonicalUrl',
                      type: 'text',
                      admin: {
                        placeholder: 'https://example.com/canonical-page',
                        description: 'Specify a canonical URL to prevent duplicate content issues. Leave empty for default.',
                      },
                    },
                    {
                      type: 'row',
                      fields: [
                        {
                          name: 'noIndex',
                          type: 'checkbox',
                          defaultValue: false,
                          admin: {
                            description: 'Prevent search engines from indexing this article',
                          },
                        },
                        {
                          name: 'noFollow',
                          type: 'checkbox',
                          defaultValue: false,
                          admin: {
                            description: 'Prevent search engines from following links in this article',
                          },
                        },
                      ],
                    },
                  ],
                },

                // Open Graph (Facebook/LinkedIn)
                {
                  type: 'collapsible',
                  label: 'Open Graph / Facebook',
                  admin: {
                    description: 'How this article appears when shared on Facebook, LinkedIn, etc.',
                    initCollapsed: true,
                  },
                  fields: [
                    {
                      name: 'ogTitle',
                      type: 'text',
                      localized: true,
                      admin: {
                        placeholder: 'Override title for social media',
                        description: 'Falls back to Meta Title or Article Title if empty',
                      },
                    },
                    {
                      name: 'ogDescription',
                      type: 'textarea',
                      localized: true,
                      admin: {
                        placeholder: 'Description for social media shares',
                        description: 'Falls back to Meta Description or Excerpt if empty',
                      },
                      maxLength: 300,
                    },
                    {
                      name: 'ogImage',
                      type: 'upload',
                      relationTo: 'media',
                      admin: {
                        description: 'Recommended: 1200x630px. Falls back to Featured Image if empty.',
                      },
                    },
                    {
                      name: 'ogType',
                      type: 'select',
                      defaultValue: 'article',
                      admin: {
                        description: 'Type of content',
                      },
                      options: [
                        { label: 'Article', value: 'article' },
                        { label: 'Website', value: 'website' },
                      ],
                    },
                  ],
                },

                // Twitter Card
                {
                  type: 'collapsible',
                  label: 'Twitter Card',
                  admin: {
                    description: 'How this article appears when shared on Twitter/X',
                    initCollapsed: true,
                  },
                  fields: [
                    {
                      name: 'twitterCard',
                      type: 'select',
                      defaultValue: 'summary_large_image',
                      admin: {
                        description: 'Card type to display on Twitter',
                      },
                      options: [
                        { label: 'Summary Card with Large Image', value: 'summary_large_image' },
                        { label: 'Summary Card', value: 'summary' },
                      ],
                    },
                    {
                      name: 'twitterTitle',
                      type: 'text',
                      localized: true,
                      admin: {
                        placeholder: 'Override title for Twitter',
                        description: 'Falls back to OG Title → Meta Title → Article Title',
                      },
                    },
                    {
                      name: 'twitterDescription',
                      type: 'textarea',
                      localized: true,
                      admin: {
                        placeholder: 'Description for Twitter cards',
                        description: 'Falls back to OG Description → Meta Description → Excerpt',
                      },
                      maxLength: 200,
                    },
                    {
                      name: 'twitterImage',
                      type: 'upload',
                      relationTo: 'media',
                      admin: {
                        description: 'Falls back to OG Image → Featured Image if empty.',
                      },
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          label: 'Author',
          fields: [
            {
              name: 'author',
              type: 'relationship',
              relationTo: 'users',
              required: true,
              admin: {
                description: 'Author of this news article',
              },
              hooks: {
                beforeChange: [
                  ({ req, operation, value }) => {
                    // Automatically set author on creation
                    if (operation === 'create' && !value && req.user) {
                      return req.user.id
                    }
                    return value
                  },
                ],
              },
            },
            {
              name: 'authorNote',
              type: 'textarea',
              localized: true,
              admin: {
                description: 'Optional note or bio from the author',
              },
            },
          ],
        },
      ],
    },
  ],
}
