import type { CollectionConfig } from 'payload'
import { generateSlug } from '@/lib/transliterate'

/**
 * News Tags Collection
 * Categories/tags for news items (Innovation, Business, Technology, Culture, etc.)
 */
export const NewsTags: CollectionConfig = {
  slug: 'news-tags',
  admin: {
    group: 'Content',
    defaultColumns: ['name', 'slug', 'updatedAt'],
    useAsTitle: 'name',
  },
  access: {
    // Public read access
    read: () => true,
    // Authenticated users can manage tags
    create: ({ req: { user } }) => !!user,
    update: ({ req: { user } }) => !!user,
    delete: ({ req: { user } }) => user?.role === 'admin',
  },
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
      localized: true,
      admin: {
        description: 'Tag name (e.g., Innovation, Business, Technology)',
      },
    },
    {
      name: 'slug',
      type: 'text',
      required: true,
      unique: true,
      admin: {
        description: 'URL-friendly identifier (auto-generated from name with Cyrillic transliteration)',
        position: 'sidebar',
      },
      hooks: {
        beforeValidate: [
          ({ data, operation, value, originalDoc }) => {
            // Auto-generate slug from name if:
            // 1. Creating a new document, OR
            // 2. Slug is empty, OR
            // 3. Slug matches what would be generated from name (auto-sync mode)
            const currentName = data?.name || ''
            const currentSlug = value || ''
            const autoGeneratedSlug = generateSlug(currentName)

            // On create, always auto-generate
            if (operation === 'create') {
              return autoGeneratedSlug
            }

            // On update, regenerate if slug is empty or matches auto-generated pattern
            if (operation === 'update') {
              // If slug is empty, generate from name
              if (!currentSlug) {
                return autoGeneratedSlug
              }

              // If slug matches what would be generated from current name, keep it in sync
              if (currentSlug === autoGeneratedSlug) {
                return autoGeneratedSlug
              }

              // If slug was previously auto-generated from old name, update to new name
              if (originalDoc?.name) {
                const oldAutoSlug = generateSlug(originalDoc.name)
                if (currentSlug === oldAutoSlug) {
                  return autoGeneratedSlug
                }
              }

              // Otherwise, user has manually edited slug, keep it
              return currentSlug
            }

            return value
          },
        ],
      },
    },
    {
      name: 'color',
      type: 'select',
      defaultValue: 'indigo',
      admin: {
        description: 'Badge color for this tag',
        position: 'sidebar',
      },
      options: [
        { label: 'Indigo', value: 'indigo' },
        { label: 'Blue', value: 'blue' },
        { label: 'Purple', value: 'purple' },
        { label: 'Green', value: 'green' },
        { label: 'Amber', value: 'amber' },
        { label: 'Red', value: 'red' },
        { label: 'Pink', value: 'pink' },
        { label: 'Teal', value: 'teal' },
      ],
    },
    {
      name: 'description',
      type: 'textarea',
      localized: true,
      admin: {
        description: 'Optional description for this tag',
      },
    },
  ],
}
